on:
  push:
    branches:
      - 'gen-sdk-updates'

name: Create Changes PR

jobs:
  create_pr:
    name: Create/Update PR

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/actions/create-pr
        with:
          draft_pr: "true"
          github_token: ${{ secrets.GITHUB_TOKEN }}
