on:
  push:
    branches:
      - 'gen-sdk-updates'

name: Create Changes PR

jobs:
  create_pr:
    name: Coding Guidelines

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/actions/create-pr
        with:
          PULL_REQUEST_DRAFT: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
